spring.datasource.url=jdbc:postgresql://localhost:5432/tg-unitau
spring.datasource.username=postgres
spring.datasource.password=7fa7200d

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true


jwt.secret=MYJWTSECRET 
jwt.expiration=3600000